name: Ping Render App

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Optional: lets you manually trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://mime-ai.onrender.com/api/ping
